### PR TITLE
Predefined globals

### PR DESCRIPTION
**Pull request by luangjokaj**
I would like to have the `variables.css` and the `globals.css` as predefined templates. 
Meaning that these two files should **never be changed** or modified in any project. If Cherry get's updated then we just upgrade the dependent clients. 

If you need additional variables on top of the Cherry ones, you should import them directly on the main entry point, which I propose to change to: `styles.css`.

So in addition the entry point becomes `styles.css` instead of `globals.css`. 

Please check the changed in the PR and let me know your thoughts.

### CODE REVIEW

**Comment by sherifsaleh** [comment]
what's @import './utilities/github.css';

**Comment by luangjokaj** [comment]
> what's @import './utilities/github.css';

It's the CSS for the syntax colour coding used only in the website documentation.

**Comment by luangjokaj** [comment]
> If I am understanding correctly, you want those 2 files to be the same, in name and content, for all projects, right? Why not store them somewhere and link directly to them in every project? Like a CDN.

Because you actually tweak the variable **values** and the mixins as well.

**Comment by valentinobaptista** [comment]
> > If I am understanding correctly, you want those 2 files to be the same, in name and content, for all projects, right? Why not store them somewhere and link directly to them in every project? Like a CDN.
> 
> Because you actually tweak the variable **values** and the mixins as well.

Will you then be able to update these files? Won't you lose your changes if you upgrade them? ("If Cherry get's updated then we just upgrade the dependent clients.")

**Comment by luangjokaj** [comment]
> > > If I am understanding correctly, you want those 2 files to be the same, in name and content, for all projects, right? Why not store them somewhere and link directly to them in every project? Like a CDN.
> > 
> > 
> > Because you actually tweak the variable **values** and the mixins as well.
> 
> Will you then be able to update these files? Won't you lose your changes if you upgrade them? ("If Cherry get's updated then we just upgrade the dependent clients.")

An update can be a change in the naming convention or additions to the current set of rules we have. So everything should be easily mapped and maintainable.

**Comment by valentinobaptista** [comment]
Probably only with a version control software like Merge Diff or so, right? Otherwise it will just override or you have to play "differences" :)
Just throwing this here because we could think on an approach like child-themes in wordpress where you don't touch core files and whenever you want to change a value you override on a separate file. This way you just update your core files without worries.

**Comment by luangjokaj** [comment]
> Probably only with a version control software like Merge Diff or so, right? Otherwise it will just override or you have to play "differences" :)
> Just throwing this here because we could think on an approach like child-themes in wordpress where you don't touch core files and whenever you want to change a value you override on a separate file. This way you just update your core files without worries.

That's why we use git, for version control. We don't have core, we don't even have a NPM library at the moment. I think you are misunderstanding me. All we have are 3 files at the moment, and some naming conventions.

Variables.css - where you add your colors and tweak the numbers to get what you need.
Globals.css - where the default styles are defined using the above variables or even more.
Mixins.css - where all repeatable chunks of css are there.

If we add another file to the convention, it could be `styles.css` we can do all the imports there. And if you have extra stuff which is not part of Cherry we keep it there. And don't mix the two. So you always are aware of the extras in the projects. And still be able to keep track of the big pattens.

I would suggest you Valentino to give it a try. It will start to become more clear, because I have a feeling you are seeing it from a different perspective and not understanding what the implications of this are directly in our everyday workflow.

So what is the decision for this proposal?

**Comment by valentinobaptista** [comment]
OK for me

**Comment by sherifsaleh** [comment]
Ok 👍

**Comment by MarkusSchaad** [comment]
ok for me

**Pull request merged**
